### ISSUE TITLE
pass multiple dburi

### ISSUE THREAD

**Issue by falgun2411** [siddharth23/cypress-postgres#1]
Hi , 
is there any way , i can pass the databaseUri to connect and query.
with this setup i can connect a single database instance only

**Comment by siddharth23** [comment]
Hi Falgun,
Thanks for your feedback. Have updated the plugin and readme to support
multiple DBS.
Let me know if any more features you expecting or facing any issues.
With Regards
Siddharth Kala

**Comment by falgun2411** [comment]
HI Siddharth, 

Thanks a lot , checked in my current code and it works fine. 
saved lot of time.
I really appreciate this quick support .
Note: If the result as multiple rows then there is array of rows , perfect.

            cy.task("dbQuery", {"query":postgres_query_getStatus,"connection":connection}).then(queryResponse => {
                console.log(queryResponse)
                cy.log(queryResponse[0].event_id)
                
                
            });

Thanks a lot.

**Comment by siddharth23** [comment]
Closing the issue as been fixed now
