### ISSUE TITLE
New Cypress (v10.x.x) configuration does not work with this file setup (cypress.json)

### ISSUE THREAD

**Issue by cinematografie** [siddharth23/cypress-postgres#7]
In Cypress > plugins > index.js the path is set to `cypress.json`, which was the default config for Cypress up until they released major version 10 in June 2022. 

Now they have a new file setup where `cypress.json` is not supported, and `cypress.json` is renamed to `cypress.config.js`. This results in the module / task for cypress-postgres not being found as it looks in the wrong path. It may be temporarily resolved with local changes, but in pipelines doing `npm install` every time to run the script, it will need to be changed in the plugin itself.

Docs are here for more information:
https://docs.cypress.io/guides/references/configuration#Configuration-File

**Comment by csutherland2020** [comment]
what are you doing for your temporary fix?

**Comment by cinematografie** [comment]
@csutherland2020 We actually had to downgrade to 9.7.0 as it was a complete blocker for us and we couldn't manage to find a fix. Our tests run in a pipeline though, and a fresh install of npm every time, so there was no way to have a local file change or similar. Have discussed a fork or writing own plugin as alternative, but not sure what else we could do apart from that (yet). Let me know if you do come up with a solution, keen to hear from others.

**Comment by Dhevesh** [comment]
For a temporary fix I have created a blank cypress.json file. This seems to fix the issue for now.

**Comment by Dhevesh** [comment]
> 

Thanks!! This works. You don't need to create a separate db.config file though, you can just point your custom function to the cypress.config.js file and it works fine.
